#version: '3.9'

name: inception

services:
  nginx:
    image: nginx
    build: requirements/nginx/
    networks:
      - network
    ports:
      - "443:443"
    volumes:
      - wp-files:/var/www/xbasabe.42.fr
    depends_on:
      - wordpress
    container_name: nginx
    restart: on-failure
  wordpress:
    image: wordpress
    build: requirements/wordpress/
    networks:
      - network
    ports:
      - "9000:9000"
    volumes:
      - wp-files:/var/www/xbasabe.42.fr
    depends_on:
      - mariadb
    container_name: wordpress
    restart: always
    env_file:
      - .env

  mariadb:
    image: mariadb
    build: requirements/mariadb/
    networks:
      - network
    volumes:
      - wp-db:/var/lib/mysql
    container_name: mariadb
    restart: always
    env_file:
      - .env

volumes:
  wp-files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/xbasabe/data/wp-files/'

  wp-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/xbasabe/data/wp-db/'

networks:
  network:
    driver: bridge
