FROM alpine:3.19

# Actualizar e instalar nginx y openssl
RUN apk -U upgrade && apk add nginx openssl

# Crear el certificado SSL autofirmado
RUN openssl req -x509 -newkey rsa:2048 -days 365 -nodes \
    -keyout /etc/ssl/private/xbasabe.42.fr_key.pem \
    -out /etc/ssl/certs/xbasabe.42.fr_cert.pem -sha256 \
    -subj "/C=MO/L=KH/OU=student/CN=xbasabe-.42.fr"

# Asignar permisos seguros a los archivos de clave y certificado
RUN chmod 600 /etc/ssl/private/xbasabe.42.fr_key.pem \
    /etc/ssl/certs/xbasabe.42.fr_cert.pem 

# Copiar la configuración de nginx personalizada
COPY conf/default.conf /etc/nginx/http.d/default.conf

# Exponer el puerto 443 para conexiones HTTPS
EXPOSE 443/tcp

# Iniciar nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
